package com.techlooper.model;

public enum EmailTemplateNameEnum {

    CITIBANK_CREDIT_CARD_PROMOTION,

    SALARY_REVIEW,

    HOW_TO_GET_PROMOTED,

    CHALLENGE_CONFIRM_ON_POST_CHALLENGE,

    CHALLENGE_CONFIRM_USER_ON_JOIN_CHALLENGE,

    CHALLENGE_NOTIFY_REGISTRANT_CHALLENGE_TIME_LINE,

    CHALLENGE_DAILY_SUMMARY,

    CHALLENGE_EMPLOYER_FEEDBACK,

    CHALLENGE_CONFIRM_USER_SUBMISSION,

    CHALLENGE_NOTIFY_PHASE_JUST_CLOSED,

    CHALLENGE_NOTIFY_EMPLOYER_UPDATE_CRITERIA,

    CHALLENGE_CONFIRM_ON_JOIN_INTERNAL_CHALLENGE,

    CHALLENGE_NOTIFY_REGISTRANT_QUALIFIED,

    PROJECT_ALERT_EMPLOYER_APPLY_JOB,

    PROJECT_ALERT_JOB_SEEKER_APPLY_JOB,

    PROJECT_ALERT_EMPLOYER_POST_JOB,

    PROJECT_ALERT_TECHLOOPIES_APPLY_JOB,

    JOB_ALERT,

    WEBINAR_ALERT_ORGANISER,

    ONBOARDING;

}
